### ISSUE TITLE
add gif to README of MXCHIP playing a gif

### ISSUE THREAD

**Issue by noopkat** [noopkat/mxchip-gifs#10]

**Comment by mtheoryx** [comment]
@noopkat What do you FOSS pros use for GIFS in readmes? And maybe this issue would be a good test of whether we have our "getting started guide" ready for devs? If it's hard to get running, you won't get a gif of any kind (aside from head-on-desk).

**Comment by mtheoryx** [comment]
I took the video you posted of the chip playing a gif from back in October/November, and converted a small section of it to a gif. It's large because I'm essentially having to do a high-framerate gif... of a gif playing on the chip.

What do you think?

![mxchip-gif-example](https://user-images.githubusercontent.com/119065/49699151-bd588d80-fb9b-11e8-862b-777df0682739.gif)
